// tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './resources/**/*.jsx',
    './resources/**/*.ts',
    './resources/**/*.tsx',
    './resources/**/*.vue',
    // Agrega aquí otros paths donde uses clases tailwind
  ],
  theme: {
    extend: {
      colors: {
        // Ejemplo si quieres extender
        // lavender: '#C084FC',
        // amber: '#FACC15',
      },
    },
  },
  safelist: [
    // Clases específicas
    'bg-red-500',
    'bg-orange-500',
    'bg-yellow-500',
    'bg-lime-500',
    'bg-green-500',
    'bg-teal-500',
    'bg-cyan-500',
    'bg-blue-500',
    'bg-indigo-500',
    'bg-violet-500',
    'bg-purple-500',
    'bg-pink-500',
    'bg-rose-500',
    'bg-gray-500',
    'bg-zinc-500',
    'bg-neutral-500',
    'bg-stone-500',
    'bg-amber-500',
    'bg-emerald-500',
    'bg-sky-500',
    'bg-fuchsia-500',
    'bg-lavender-500',

    'bg-red-100',
    'bg-orange-100',
    'bg-yellow-100',
    'bg-lime-100',
    'bg-green-100',
    'bg-teal-100',
    'bg-cyan-100',
    'bg-blue-100',
    'bg-indigo-100',
    'bg-violet-100',
    'bg-purple-100',
    'bg-pink-100',
    'bg-rose-100',
    'bg-gray-100',
    'bg-zinc-100',
    'bg-neutral-100',
    'bg-stone-100',
    'bg-amber-100',
    'bg-emerald-100',
    'bg-sky-100',
    'bg-fuchsia-100',
    'bg-lavender-100',
    // etc según los que usas

    // Hover border de colores
    'hover:border-red-500',
    'hover:border-orange-500',
    'hover:border-yellow-500',
    'hover:border-lime-500',
    'hover:border-green-500',
    'hover:border-teal-500',
    'hover:border-cyan-500',
    'hover:border-blue-500',
    'hover:border-indigo-500',
    'hover:border-violet-500',
    'hover:border-purple-500',
    'hover:border-pink-500',
    'hover:border-rose-500',
    'hover:border-gray-500',
    'hover:border-zinc-500',
    'hover:border-neutral-500',
    'hover:border-stone-500',
    'hover:border-amber-500',
    'hover:border-emerald-500',
    'hover:border-sky-500',
    'hover:border-fuchsia-500',
    'hover:border-lavender-500',

    // ring-{color}-500 para los anillos de enfoque
    'ring-red-500',
    'ring-orange-500',
    'ring-yellow-500',
    'ring-lime-500',
    'ring-green-500',
    'ring-teal-500',
    'ring-cyan-500',
    'ring-blue-500',
    'ring-indigo-500',
    'ring-violet-500',
    'ring-purple-500',
    'ring-pink-500',
    'ring-rose-500',
    'ring-gray-500',
    'ring-zinc-500',
    'ring-neutral-500',
    'ring-stone-500',
    'ring-amber-500',
    'ring-emerald-500',
    'ring-sky-500',
    'ring-fuchsia-500',
    'ring-lavender-500',


    // text-{color}-500 para los textos coloreados
    'text-red-500',
    'text-orange-500',
    'text-yellow-500',
    'text-lime-500',
    'text-green-500',
    'text-teal-500',
    'text-cyan-500',
    'text-blue-500',
    'text-indigo-500',
    'text-violet-500',
    'text-purple-500',
    'text-pink-500',
    'text-rose-500',
    'text-gray-500',
    'text-zinc-500',
    'text-neutral-500',
    'text-stone-500',
    'text-amber-500',
    'text-emerald-500',
    'text-sky-500',
    'text-fuchsia-500',
    'text-lavender-500',

    {
      // Patrón regex para bg, border, text dinámico con variantes hover
      pattern: /^(bg|text|border)-(red|blue|rose|sky|green|yellow|purple|pink|indigo|teal|cyan|orange|violet|amber|emerald)-(100|500)$/,
      variants: ['hover'],
    },
  ],
  plugins: [
  ],
};
